In [2]:
import ase
import ase.io
from ase.io import xsf
import pandas as pd
import json
import seaborn as sns
import matplotlib.pyplot as plt
import os
import numpy as np
%matplotlib inline

/Users/mohammad/anaconda3/lib/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [3]:
dataframe_df2 = pd.read_pickle("DataFrame_df2.pkl")
dataframe_df2.head()

uuid  \
0  dec2d070-d2ad-41f3-b742-786368ade33a   
1  51e630e8-d94f-421c-bd1e-3e2f298e740c   
2  527e7b32-d211-4743-9631-120122819190   
3  37bf14b1-6529-436c-a519-e1ad9b208784   
4  e7a9cec3-f11a-4d16-a8c5-ebd758bb6592   

                                           structure  \
0  (Atom('Cd', [-0.0, -0.0, 29.0441583], index=0)...   
1  (Atom('Fe', [0.0, 0.0, 0.0], index=0), Atom('C...   
2  (Atom('Er', [2.1386, 4.301805, 3.209025], inde...   
3  (Atom('Ba', [0.0, 0.0, 9.5697], index=0), Atom...   
4  (Atom('Ba', [0.0, 2.414, 1.49473], index=0), A...   

                                                cell      volume  \
0  [[2.1044124705, 1.2149831063, 34.279850741], [...  525.885600   
1  [[3.35814166734363, 3.21879556184565e-14, -3.2...   52.188194   
2  [[2.14789490163679, -12.5878501270869, 0.0], [...  232.520056   
3  [[-2.0745739339, 2.0745739339, 7.4278571834], ...  127.873741   
4  [[4.6829418165, 0.0, 0.0], [0.0, 4.6829418165,...  166.823529   

   relevant_dimension_of_highest_dimensionality_substructure  \
0                                          15.340954           
1                                           9.766268           
2                                          18.471785           
3                                          17.215428           
4                                          21.929944           

   binding_energy_per_substructure  binding_energy label  \
0                        -0.165000       10.755509    EE   
1                        -0.149888       15.347484    EE   
2                        -0.454048       24.580650    EE   
3                        -0.747937       43.445746    PE   
4                        -0.532853       24.297979    EE   

   number_of_atoms_in_bulk  \
0                       15   
1                        3   
2                        8   
3                        3   
4                        6   

   number_of_highest_dimensionality_substructures_in_bulk  \
0                                                  5        
1                                                  1        
2                                                  1        
3                                                  1        
4                                                  1        

                                   sub_structure_spg sub_structure_dim  \
0  [C2/m (12), C2/m (12), C2/m (12), C2/m (12), C...   [2, 2, 2, 2, 2]   
1                                      [P-3m1 (164)]               [2]   
2                                      [P2_1/m (11)]               [2]   
3                                        [C2/m (12)]               [2]   
4                                     [P4/nmm (129)]               [2]   

    energy_bulk           sub_structure_formula  \
0 -17198.871453  [CdI2, CdI2, CdI2, CdI2, CdI2]   
1  -5361.474444                         [Cl2Fe]   
2 -26090.090963                        [Er2Te6]   
3  -2866.173187                         [Ba2Hg]   
4  -3217.539658                       [Ba2H2I2]   

                        PMG Structure from ASE Atoms  
0  [[ 0.         0.        29.0441583] Cd, [ 0.  ...  
1  [[0. 0. 0.] Fe, [0.         2.06980071 4.36433...  
2  [[2.1386   4.301805 3.209025] Er, [ 2.1386   -...  
3  [[0.     0.     9.5697] Ba, [0.     0.     5.6...  
4  [[0.      2.414   1.49473] Ba, [2.414   0.    ...

In [7]:
dataframe_df2.columns

Index(['uuid', 'structure', 'cell', 'volume',
       'relevant_dimension_of_highest_dimensionality_substructure',
       'binding_energy_per_substructure', 'binding_energy', 'label',
       'number_of_atoms_in_bulk',
       'number_of_highest_dimensionality_substructures_in_bulk',
       'sub_structure_spg', 'sub_structure_dim', 'energy_bulk',
       'sub_structure_formula', 'PMG Structure from ASE Atoms'],
      dtype='object')

In [8]:
structures = list(dataframe_df2["PMG Structure from ASE Atoms"])
gridpoints = list(dataframe_df2.index)

In [9]:
features = {n:{} for n in gridpoints}
for name in gridpoints:
    features[name]["structure"]=dataframe_df2["PMG Structure from ASE Atoms"][name]

In [10]:
data=pd.DataFrame.from_dict(features).T
data

structure
0     [[ 0.         0.        29.0441583] Cd, [ 0.  ...
1     [[0. 0. 0.] Fe, [0.         2.06980071 4.36433...
2     [[2.1386   4.301805 3.209025] Er, [ 2.1386   -...
3     [[0.     0.     9.5697] Ba, [0.     0.     5.6...
4     [[0.      2.414   1.49473] Ba, [2.414   0.    ...
...                                                 ...
2387  [[0.         2.87064327 2.285     ] Li, [2.486...
2388  [[ 8.7759233  -1.51816627  6.20947541] K, [ 2....
2389  [[6.06416256 0.5661043  0.86358119] Li, [4.004...
2390  [[0.        0.        2.4314841] Sc, [ 0.     ...
2391  [[0. 0. 0.] Co, [ 1.50622572 -0.52728089  5.01...

[2392 rows x 1 columns]

In [16]:
data_small = data [data.index < 101]

In [12]:
%matplotlib inline
from matplotlib import pyplot as plt
from matminer.datasets import load_dataset
from matminer.featurizers.base import MultipleFeaturizer
from matminer.featurizers.composition import ElementProperty, Stoichiometry, ValenceOrbital, IonProperty
from matminer.featurizers.structure import (SiteStatsFingerprint, StructuralHeterogeneity,
                                            ChemicalOrdering, StructureComposition, MaximumPackingEfficiency)
from matminer.featurizers.conversions import DictToObject
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import ShuffleSplit, train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from scipy import stats
from tqdm import tqdm_notebook as tqdm
import numpy as np

In [13]:
featurizer = MultipleFeaturizer([
    SiteStatsFingerprint.from_preset("CoordinationNumber_ward-prb-2017"),
    StructuralHeterogeneity(),
    ChemicalOrdering(),
    MaximumPackingEfficiency(),
    SiteStatsFingerprint.from_preset("LocalPropertyDifference_ward-prb-2017"),
    StructureComposition(Stoichiometry()),
    StructureComposition(ElementProperty.from_preset("magpie")),
    StructureComposition(ValenceOrbital(props=['frac'])),
    StructureComposition(IonProperty(fast=True))
])

In [14]:
dto = DictToObject(target_col_id='structure', overwrite_data=True)
data = dto.featurize_dataframe(data, 'structure')

DictToObject:   0%|          | 0/2392 [00:00<?, ?it/s]

***Let's featurize our datasets:***

In [45]:
%%time
X = featurizer.featurize_many(data['structure'], ignore_errors=True)

MultipleFeaturizer:   0%|          | 0/2392 [00:00<?, ?it/s]

CPU times: user 3.78 s, sys: 2.2 s, total: 5.98 s
Wall time: 1h 11min 28s


***Convert our generated features into DataFrame and add the label, and finally save it as pickle file***

In [ ]:
df_features = pd.DataFrame(X)
df_features.head()

In [ ]:
df = pd.concat([df_feature, y], axis = 1)

In [ ]:
df.to_pickle('features_MultipleFeaturizer.pkl')

In [32]:
df = pd.read_pickle("features_MultipleFeaturizer.pkl")
df.head()

0          1         2          3         4         5         6  \
0        NaN        NaN       NaN        NaN       NaN       NaN       NaN   
1   6.000000  10.432235  4.432235   8.954823  1.969882  0.101871  1.076403   
2   9.052693  11.479272  2.426579   9.749345  0.864963  0.020033  1.032994   
3  10.187778  12.638871  2.451093  11.821840  1.089375  0.050764  1.038073   
4   9.198422  14.426225  5.227803  11.335849  2.060251  0.087363  1.131045   

          7             8         9  ...        264    265       266  \
0       NaN           NaN       NaN  ...  57.777778   64.0  0.130435   
1  0.847193  1.119514e-11  0.171207  ...  73.333333   64.0  0.272727   
2  0.959935  2.631480e-02  0.125121  ...  15.750000  152.0  0.129032   
3  0.923854  4.593043e-02  0.102799  ...  28.000000  229.0  0.200000   
4  0.914155  9.864448e-02  0.120736  ...  65.555556   64.0  0.250000   

        267       268       269  270       271       272  label  
0  0.217391  0.652174  0.000000  1.0  0.209607  0.046579     EE  
1  0.454545  0.272727  0.000000  1.0  0.357395  0.079421     EE  
2  0.193548  0.483871  0.193548  0.0  0.168813  0.031652     EE  
3  0.000000  0.333333  0.466667  0.0  0.265103  0.058912     PE  
4  0.250000  0.500000  0.000000  1.0  0.543070  0.104828     EE  

[5 rows x 274 columns]

**Number of features that are generated for each structure:**

In [37]:
X = np.array(df.drop('label', axis = 1))
print('Input data shape:', X.shape)

Input data shape: (2392, 273)


***Number of featurization that are failed:***

In [38]:
import pandas as pd
failed = np.any(pd.isnull(X), axis=1)
print('Number failed: {}/{}'.format(np.sum(failed), len(failed)))

Number failed: 179/2392


***Random Forest Classifier:***

In [39]:
model = Pipeline([
    ('imputer', SimpleImputer()), # For the failed structures
    ('model', RandomForestClassifier(n_estimators=150, n_jobs=-1))
])

In [40]:
y = df['label']

***Train Test Split***

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

***Train the model and predict:***

In [42]:
model.fit(X_train,y_train)

Pipeline(steps=[('imputer', SimpleImputer()),
                ('model', RandomForestClassifier(n_estimators=150, n_jobs=-1))])

In [43]:
predictions = model.predict(X_test)

***Evaluation***

In [44]:
from sklearn.metrics import classification_report, confusion_matrix

In [45]:
print(classification_report(y_test,predictions))
print('\n')
print(confusion_matrix(y_test,predictions))

              precision    recall  f1-score   support

          EE       0.83      0.84      0.84       341
         HBE       0.74      0.71      0.73       167
          PE       0.66      0.67      0.67       210

    accuracy                           0.76       718
   macro avg       0.74      0.74      0.74       718
weighted avg       0.76      0.76      0.76       718



[[286  18  37]
 [ 13 119  35]
 [ 45  24 141]]


***Let train in a binary case: EE and HBE***

In [46]:
df_binary = df.replace(to_replace='PE', value = 'EE')
final_df_binary = pd.get_dummies(df_binary,columns=['label'],drop_first=True)

In [47]:
final_df_binary.head()

0          1         2          3         4         5         6  \
0        NaN        NaN       NaN        NaN       NaN       NaN       NaN   
1   6.000000  10.432235  4.432235   8.954823  1.969882  0.101871  1.076403   
2   9.052693  11.479272  2.426579   9.749345  0.864963  0.020033  1.032994   
3  10.187778  12.638871  2.451093  11.821840  1.089375  0.050764  1.038073   
4   9.198422  14.426225  5.227803  11.335849  2.060251  0.087363  1.131045   

          7             8         9  ...        264    265       266  \
0       NaN           NaN       NaN  ...  57.777778   64.0  0.130435   
1  0.847193  1.119514e-11  0.171207  ...  73.333333   64.0  0.272727   
2  0.959935  2.631480e-02  0.125121  ...  15.750000  152.0  0.129032   
3  0.923854  4.593043e-02  0.102799  ...  28.000000  229.0  0.200000   
4  0.914155  9.864448e-02  0.120736  ...  65.555556   64.0  0.250000   

        267       268       269  270       271       272  label_HBE  
0  0.217391  0.652174  0.000000  1.0  0.209607  0.046579          0  
1  0.454545  0.272727  0.000000  1.0  0.357395  0.079421          0  
2  0.193548  0.483871  0.193548  0.0  0.168813  0.031652          0  
3  0.000000  0.333333  0.466667  0.0  0.265103  0.058912          0  
4  0.250000  0.500000  0.000000  1.0  0.543070  0.104828          0  

[5 rows x 274 columns]

In [48]:
X = final_df_binary.drop('label_HBE', axis = 1).values
y = final_df_binary['label_HBE'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [49]:
model = Pipeline([
    ('imputer', SimpleImputer()), # For the failed structures
    ('model', RandomForestClassifier(n_estimators=150, n_jobs=-1))
])

In [50]:
model.fit(X_train,y_train)

Pipeline(steps=[('imputer', SimpleImputer()),
                ('model', RandomForestClassifier(n_estimators=150, n_jobs=-1))])

In [51]:
X_train.shape

(1674, 273)

In [52]:
predictions = model.predict(X_test)

In [53]:
print(classification_report(y_test,predictions))
print('\n')
print(confusion_matrix(y_test,predictions))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92       551
           1       0.85      0.56      0.68       167

    accuracy                           0.88       718
   macro avg       0.87      0.77      0.80       718
weighted avg       0.87      0.88      0.87       718



[[535  16]
 [ 73  94]]
